import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#004820",
        "surface-container-high": "#1d2023",
        "primary-fixed-dim": "#24f07e",
        "tertiary-fixed": "#efb1f9",
        "on-primary": "#005d2c",
        surface: "#0c0e10",
        "on-primary-fixed-variant": "#006832",
        "inverse-primary": "#006e35",
        "secondary-fixed": "#b1efd8",
        "on-tertiary": "#673573",
        "surface-container-highest": "#232629",
        "on-secondary-fixed-variant": "#296654",
        "on-secondary-container": "#9fddc6",
        "on-tertiary-fixed-variant": "#673573",
        "surface-dim": "#0c0e10",
        "surface-variant": "#232629",
        outline: "#747578",
        "surface-container-lowest": "#000000",
        "on-surface": "#f1f0f3",
        "on-primary-container": "#004f24",
        "on-secondary": "#1d5c4a",
        "secondary-container": "#0d503f",
        "outline-variant": "#46484a",
        "primary-fixed": "#3fff8b",
        "primary-container": "#13ea79",
        "surface-container-low": "#111416",
        "inverse-on-surface": "#545557",
        error: "#ff716c",
        "on-surface-variant": "#aaabad",
        "secondary-dim": "#a3e1ca",
        "surface-bright": "#292c30",
        "on-error": "#490006",
        primary: "#3fff8b",
        tertiary: "#f8c3ff",
        "tertiary-dim": "#e0a4ea",
        "tertiary-fixed-dim": "#e0a4ea",
        "tertiary-container": "#efb1f9",
        "on-secondary-fixed": "#004938",
        background: "#0c0e10",
        "surface-container": "#171a1c",
        "error-dim": "#d7383b",
        "inverse-surface": "#f9f9fc",
        "on-tertiary-container": "#5d2c69",
        "secondary-fixed-dim": "#a3e1ca",
        "on-tertiary-fixed": "#471653",
        secondary: "#b1efd8",
        "surface-tint": "#3fff8b",
        "error-container": "#9f0519",
        "primary-dim": "#24f07e",
        "on-error-container": "#ffa8a3",
        "on-background": "#f1f0f3",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
